apiVersion: apps/v1
kind: Deployment
metadata:
  # The namespace of the application
  name: weather-app
spec:
  replicas: 2
  # This specifies the label selector used to match pods to the Deployment
  selector:
    matchLabels:
      app: weather-app
  # This specifies the Pod template used to create the replicas
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      # This specifies the container specification for the weather-app container.
      containers:
      - name: weather-app
        image: sigler05/weather_app:k8s_deployment 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-ingress
  #namespace: ingress-nginx
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-app-service
                port:
                  number: 80

